name: super_editor
repository: https://github.com/superlistapp/super_editor

packages:
  - super_editor/pubspec.yaml
  - super_editor/example/pubspec.yaml
  - super_editor_markdown/pubspec.yaml
  - super_text_layout/pubspec.yaml
  - super_text_layout/example/pubspec.yaml
  - attributed_text/pubspec.yaml
  - website/pubspec.yaml

command:
  bootstrap:
   usePubspecOverrides: true