name: super_editor
repository: https://github.com/superlistapp/super_editor

packages:
  - super_editor
  - super_editor/example
  - super_editor_markdown
  - super_text_layout
  - super_text_layout/example
  - attributed_text
  - golden_runner
  - website
